### ISSUE TITLE
Enchantment level problem

### ISSUE THREAD

**Issue by moeKiwiSAMA** [Agenda-Minecraft/UltimateInventoryShop#1]
Exception:
```
java.lang.IllegalArgumentException: Enchantment level is either too low or too high (given 9, bounds a
re 1 to 4)                                                                                                    at org.bukkit.inventory.ItemStack.addEnchantment(ItemStack.java:399) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.addEnchantments(ItemStack.java:380) ~[paper-api-1.19.2-R0.1-
SNAPSHOT.jar:?]
        at cat.kiwi.minecraft.uis.model.pojo.GoodPojoKt.getRenderedGoods(GoodPojo.kt:56) ~[UltimateInv
entoryShop-1.0.0-rc6-all.jar:?]
        at cat.kiwi.minecraft.uis.utils.InventoryKt.fillAndPadding(Inventory.kt:56) ~[UltimateInventoryShop-1.0.0-rc6-all.jar:?]
        at cat.kiwi.minecraft.uis.utils.InventoryKt.fillAndPadding$default(Inventory.kt:50) ~[Ultimate
InventoryShop-1.0.0-rc6-all.jar:?]
        at cat.kiwi.minecraft.uis.utils.InventoryKt.fillTable(Inventory.kt:71) ~[UltimateInventoryShop
-1.0.0-rc6-all.jar:?]
        at cat.kiwi.minecraft.uis.controller.InventoryBaseStructureController.initGeneralStructure$lam
bda-0(InventoryBaseStructureController.kt:62) ~[UltimateInventoryShop-1.0.0-rc6-all.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.
jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pape
r-1.19.2.jar:git-Paper-307]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper
.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by moeKiwiSAMA** [comment]
Bukkit method "add Enchantment" checks enchantment levels.
``` java
    @Utility
    public void addEnchantment(@NotNull Enchantment ench, int level) {
        Preconditions.checkArgument(ench != null, "Enchantment cannot be null");
        if ((level < ench.getStartLevel()) || (level > ench.getMaxLevel())) {
            throw new IllegalArgumentException("Enchantment level is either too low or too high (given " + level + ", bounds are " + ench.getStartLevel() + " to " + ench.getMaxLevel() + ")");
        } else if (!ench.canEnchantItem(this)) {
            throw new IllegalArgumentException("Specified enchantment cannot be applied to this itemstack");
        }

        addUnsafeEnchantment(ench, level);
    }
```
UIS gives a option in config file to use unsafe enchantment method
